export const ONE_YEAR_IN_SECONDS = 60 * 60 * 24 * 365;

export const THEME_PREFERENCE_KEY = "ALEXBON_THEME";
export const THEME_COOKIE = THEME_PREFERENCE_KEY;
export const THEME_COOKIE_MAX_AGE = ONE_YEAR_IN_SECONDS;

export const LOCALE_PREFERENCE_KEY = "ALEXBON_LOCALE";
export const LOCALE_COOKIE = LOCALE_PREFERENCE_KEY;
export const LOCALE_COOKIE_MAX_AGE = ONE_YEAR_IN_SECONDS;
